steps:
# first try - WIP
- name: 'us-central1-docker.pkg.dev/thomashk-mig/clustertoolkit-docker-repo/gcluster-image:1.64.0'
  id: 'Deploy cluster w gcluster image'
  entrypoint: 'gcluster'
  args:
    # THe 'destroy' command for creating a new cluster 
    - 'destroy'
    - 'a3mega-lustre-base'
    - '--auto-approve'