steps:
# first try - WIP
- name: 'us-central1-docker.pkg.dev/thomashk-mig/clustertoolkit-docker-repo/gcluster-image:1.64.0'
  id: 'Deploy cluster w gcluster image'
  entrypoint: 'gcluster'
  args:
    # THe 'deploy' command for creating a new cluster 
    - 'deploy'
    - '-d'
    - 'deploymentset/a3mega-slurm-deployment-thomashk.yaml'
    - '-w'
    - 'deploymentset/a3mega-lustre-slurm-blueprint.yaml'
  #  - '--blackend-config'
  #  - 'bucket=thomashk-clustertoolkit'
    - '--auto-approve'


#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: bash
#    args:
#    - "-c"
#    - docker run --network=cloudbuild us-central1-docker.pkg.dev/thomashk-mig/clustertoolkit-docker-repo/gcluster-image:1.64.0 /bin/bash deployment.sh a3mega-slurm-deployment-thomashk.yaml a3mega-lustre-slurm-blueprint.yaml out thomashk-gcsfuse

# What did not work: 
#    - docker run -v ~/.config/gcloud/:/root/.config/gcloud us-central1-docker.pkg.dev/thomashk-mig/clustertoolkit-docker-repo/gcluster-image:1.64.0 /bin/bash deployment.sh a3mega-slurm-deployment-thomashk.yaml a3mega-lustre-slurm-blueprint.yaml out thomashk-gcsfuse

#    script: |
#      docker run -v ~/.config/gcloud/:/root/.config/gcloud us-central1-docker.pkg.dev/thomashk-mig/clustertoolkit-docker-repo/gcluster-image:1.64.0 /bin/bash deployment.sh a3mega-slurm-deployment-thomashk.yaml a3mega-lustre-slurm-blueprint.yaml out thomashk-gcsfuse